### ISSUE TITLE
[Bug]: Private video with graphql plugin

### ISSUE THREAD

**Issue by Tommo56700** [apivideo/api.video-strapi-plugin#12]
### Version

1.0.1

### Environment that reproduces the issue

@strapi/strapi: 4.6.0
@strapi/plugin-graphql: 4.6.0

### Is it reproducible in the example application?

No

### Reproduction steps

1. Setup an example strapi application
2. Install api.video plugin and upload a private video
3. Install graphql plugin: https://docs.strapi.io/dev-docs/plugins/graphql
4. Use the below graphql plugin config:
```
graphql: {
    config: {
      endpoint: '/graphql',
      shadowCRUD: true,
      playgroundAlways: false,
      federation: true,
      apolloServer: {
        introspection: true,
      }
    },
  }
```
5. Hit the graphql endpoint with the following query:
```
{apiVideoUploaderApiVideoAssets{data{attributes{title, videoId, player}}}}
```

### Expected result

Expect results with a newly generated private video token with each request

### Actual result

Results are returned with the default token on each request:
`token=11111111-1111-1111-1111-111111111111`

### Additional context

First off, great work on the private video feature, it seems to work flawlessly with the REST API. My understanding is that the shadow CRUD operations generated by the Strapi grapql plugin most likely call the default entity service, therefore skipping the custom logic introduced for private videos in the content-api controller. As this is an official strapi plugin, can we get this to work natively within the api.video plugin? If not, a potential workaround would be to implement custom resolver login in the client application that calls the controller directly (https://strapi.io/blog/extending-and-building-custom-resolvers-with-strapi-v4). Here's the example code:
```
apiVideoUploaderApiVideoAsset: {
    resolve: async (parent, args, context) => {
        const { toEntityResponse } = strapi.service(
            "plugin::graphql.format"        ).returnTypes;
        const id = args.id;
        const ctx = {params: {id}}
        var result = await strapi.plugin('api-video-uploader').controller('content-api').findOne(ctx);
        const response = toEntityResponse(result)
        return response;
    }
}
```

Can the team confirm if this is the correct approach?

**Comment by olivierapivideo** [comment]
Hi @Tommo56700 ,

This issue is fixed in v1.0.2
