### ISSUE TITLE
Enable private video upload & management

### ISSUE THREAD

**Issue by Tommo56700** [apivideo/api.video-strapi-plugin#7]
Currently it is not possible to upload videos as private from the Strapi plugin. As a user with a requirement to keep video secure at all times we need this to be possible.

Add a toggle for private video to the Strapi upload page. We should be able to then watch and manage private video using the api key for auth. This should be handled behind the scenes.

**Comment by promathieuthiry** [comment]
Great idea, we add it in our roadmap for 2023.

**Comment by Tommo56700** [comment]
Here's a first draft. What are your thoughts on token management - I just went with something I could get working.

**Comment by olivierapivideo** [comment]
It is deployed (version 1.0.1) 
Thank you very much for your contribution @Tommo56700 !
